---
- hosts: development ##You can change this to `all` to run for all hosts defined in `inventories/hosts`
  gather_facts: yes
  become: yes
#  vars:
#    plugins:
#      - apache
#      - nginx
#      - mongo
#      - mysql
#      - rabbitmq
  roles:
    - serverdensity
